# Generated by Django 5.2 on 2025-04-21 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_sigla_cliente_sub_local_cliente_unidade'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('medio', 'Médio'), ('grave', 'Grave')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('etiqueta', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('codigo_referencia', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('situacao', models.CharField(choices=[('em_contrato', 'Em contrato'), ('sem_contrato', 'Sem contrato')], default='em_contrato', max_length=20)),
                ('status', models.CharField(choices=[('em_producao', 'Em Produção'), ('disponivel', 'Disponível'), ('em_manutencao', 'Em Manutenção'), ('danificado', 'Danificado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('data_garantia', models.DateField(blank=True, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('fornecedores', models.CharField(blank=True, max_length=255)),
                ('utilizado_por', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_alterados', to='usuarios.usuario')),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_cadastrados', to='usuarios.usuario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.categoriaequipamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('parametros_personalizados', models.ManyToManyField(blank=True, to='equipamentos.parametroequipamento')),
            ],
        ),
    ]
