# Generated by Django 5.2 on 2025-04-21 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='localizacao',
        ),
        migrations.CreateModel(
            name='ParametroPadraoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.categoriaequipamento')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.parametroequipamento')),
            ],
            options={
                'unique_together': {('categoria', 'parametro')},
            },
        ),
    ]
