# Generated by Django 5.2 on 2025-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_remove_equipamento_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaequipamento',
            name='parametros',
            field=models.ManyToManyField(blank=True, to='equipamentos.parametroequipamento'),
        ),
        migrations.DeleteModel(
            name='ParametroPadraoCategoria',
        ),
    ]
