# Generated by Django 5.2 on 2025-04-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_categoriaequipamento_parametros_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaequipamento',
            old_name='parametros',
            new_name='parametros_personalizados',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='parametros_personalizados',
        ),
    ]
