# Generated by Django 5.2 on 2025-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_rename_parametros_categoriaequipamento_parametros_personalizados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaequipamento',
            old_name='parametros_personalizados',
            new_name='parametros',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='parametros_personalizados',
            field=models.ManyToManyField(blank=True, to='equipamentos.parametroequipamento'),
        ),
    ]
