# Generated by Django 5.2 on 2025-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_rename_parametros_personalizados_categoriaequipamento_parametros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroequipamento',
            name='avaliacao_ajuda',
            field=models.TextField(blank=True, help_text='Descreva como o analista deve avaliar este parâmetro.', verbose_name='Como avaliar'),
        ),
    ]
