# Generated by Django 5.2 on 2025-05-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_parametroequipamento_avaliacao_ajuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametroequipamento',
            name='gravidade',
        ),
    ]
