# Generated by Django 5.2 on 2025-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_remove_parametroequipamento_gravidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroequipamento',
            name='avaliacao_ajuda',
            field=models.CharField(blank=True, max_length=300, verbose_name='Como avaliar o parâmetro'),
        ),
    ]
