# Generated by Django 5.2 on 2025-05-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Vistoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
