# Generated by Django 5.2 on 2025-04-17 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/')),
                ('assinatura', models.ImageField(blank=True, null=True, upload_to='usuarios/assinaturas/')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista')], default='analista', max_length=10)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
