# Generated by Django 5.2 on 2025-04-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_sigla_cliente_sub_local_cliente_unidade'),
        ('equipamentos', '0005_rename_parametros_personalizados_categoriaequipamento_parametros_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100)),
                ('sublocal', models.CharField(blank=True, max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VistoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistoriado_em', models.DateTimeField(auto_now_add=True)),
                ('status_final', models.CharField(choices=[('em_producao', 'Em Produção'), ('disponivel', 'Disponível'), ('em_manutencao', 'Em Manutenção'), ('danificado', 'Danificado'), ('indisponivel', 'Indisponível')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos_vistoriados', to='vistorias.vistoria')),
            ],
            options={
                'unique_together': {('vistoria', 'equipamento')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('ok', 'OK'), ('observacao', 'Observação'), ('critico', 'Crítico')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.parametroequipamento')),
                ('vistoria_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='vistorias.vistoriaequipamento')),
            ],
            options={
                'unique_together': {('vistoria_equipamento', 'parametro')},
            },
        ),
    ]
