# Generated by Django 5.2 on 2025-04-25 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoria',
            name='horario_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
