# Generated by Django 5.2 on 2025-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0002_alter_vistoria_horario_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoparametro',
            name='situacao',
            field=models.CharField(choices=[('ok', 'OK'), ('danificado', 'Danificado')], max_length=20),
        ),
    ]
