# Generated by Django 5.2 on 2025-04-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0003_alter_avaliacaoparametro_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vistoriaequipamento',
            options={'ordering': ['-vistoriado_em']},
        ),
        migrations.AlterUniqueTogether(
            name='vistoriaequipamento',
            unique_together=set(),
        ),
    ]
