# Generated by Django 5.2 on 2025-05-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0004_alter_vistoriaequipamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoparametro',
            name='gravidade',
            field=models.CharField(blank=True, choices=[('leve', 'Leve'), ('medio', 'Médio'), ('grave', 'Grave')], help_text='Gravidade do problema, se danificado', max_length=10, null=True),
        ),
    ]
