# Generated by Django 5.2 on 2025-04-18 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('responsavel', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clientes/logos/')),
                ('numero_contrato', models.CharField(blank=True, max_length=100)),
                ('data_inicio_contrato', models.DateField(blank=True, null=True)),
                ('data_vencimento_contrato', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
