# Generated by Django 5.2 on 2025-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sigla do Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sub_local',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sub-local'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='unidade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
