# Generated by Django 5.2 on 2025-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_sigla_cliente_sub_local_cliente_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_inicio_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_vencimento_contrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
