# Generated by Django 5.2 on 2025-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_data_inicio_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_vencimento_contrato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
