# Generated by Django 5.2 on 2025-05-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_data_inicio_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
