# Generated by Django 5.2 on 2025-05-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
    ]
